### ISSUE TITLE
Add Colorblind options from nightfox.nvim

### ISSUE THREAD

**Issue by peterkos** [ssaunderss/zed-nightfox#2]
It would be really neat to have the [colorblind customization options](https://github.com/EdenEast/nightfox.nvim?tab=readme-ov-file#colorblind) that are in `nightfox.nvim`. Not sure what's possible via Zed's extension API.

**Comment by ssaunderss** [comment]
Hi @peterkos, this currently isn't possible via their extension API. It _might_ be possible to author a WASM extension that provides customization options for all themes and lets you customize colorblind settings via a [slash command](https://zed.dev/docs/extensions/slash-commands).

I also checked [zed's core repo issue tracker](https://github.com/zed-industries/zed/issues) and didn't see any issues for this - this is a great issue that I think could gain some more traction over there!

Going to close this issue because both solutions would live outside of this extension.

**Comment by peterkos** [comment]
Thanks for looking into it!

Forever ago I wanted to use the Nightfox themes for my blog's code snippet syntax highlighting, and it was a [chore](https://github.com/peterkos/peterkos.github.io/blob/main/highlight_themes/readme.md) to get everything in the right format. Appreciate the work of this extension :)
